//! mxm-mono-02's routing parameters: one presence and one amount per *(target, source)* pair.
//!
//! `plans/plan-mxm-mono-02-modulation.md` §3 and §4. The derive needs concrete fields and this
//! instrument's source list is its own, so the struct is declared here — `mxm-mono-01`'s shape.
//! [`mxm_modulation_params`] reads the fields, and [`mxm_mono_02_dsp::routing`] evaluates them.
//!
//! # Permanent ids
//!
//! One `#[nested(id_prefix = …)]` per target, so a pair's ids are `mod_<target>_<source>` and
//! `mod_<target>_<source>on`. **Permanent from here on**, like every id in this collection.
//!
//! # Seventeen ids retired, and none may come back
//!
//! [`RETIRED_IDS`]: first the nine controls the conversion replaced — the modulator's two depths, the
//! auto bend, the pulse-width section's depth and source switch, the envelope's depth and three-way
//! switch, keyboard tracking and the bender's cutoff sensitivity. Each is an owner decision under the
//! governing plan's decision 1.13, and each state they could reach is reachable by routes
//! (`mxm-mono-02-dsp`'s `tests/legacy_reachability.rs`) but the envelope switch's follower position.
//! Then the Follower source's eight route ids, when the external input it followed was removed (the
//! owner, 2026-09-26). A name whose meaning changed must not be quietly re-used.

use mxm_modulation_params::Route;
use mxm_modulation_params::reading::{self, Fader, Reach};
use mxm_mono_02_dsp::routing::{
    self, INIT_PRESENT, KEY_UNIT_SEMITONES, Routing, SOURCE_NAMES, SOURCES, TARGET_NAMES, TARGETS,
    offer, source, target,
};
use nice_plug::prelude::*;

/// Every routing pair's two permanent ids, `(amount, presence)`, in `[target][source]` order.
///
/// Written out so a permanent id can be read, grepped and diffed; generated by the
/// `#[nested(id_prefix = …)]` groups in [`Routes`], and
/// `tests::the_id_table_is_what_the_derive_actually_produces` holds the two together.
pub const ROUTE_IDS: [[(&str, &str); SOURCES]; TARGETS] = [
    [
        ("mod_pitch_lfo", "mod_pitch_lfoon"),
        ("mod_pitch_lfowidth", "mod_pitch_lfowidthon"),
        ("mod_pitch_env", "mod_pitch_envon"),
        ("mod_pitch_autobend", "mod_pitch_autobendon"),
        ("mod_pitch_key", "mod_pitch_keyon"),
        ("mod_pitch_vel", "mod_pitch_velon"),
        ("mod_pitch_wheel", "mod_pitch_wheelon"),
        ("mod_pitch_press", "mod_pitch_presson"),
        ("mod_pitch_bend", "mod_pitch_bendon"),
        ("mod_pitch_vco1", "mod_pitch_vco1on"),
        ("mod_pitch_vco2", "mod_pitch_vco2on"),
        ("mod_pitch_sub", "mod_pitch_subon"),
        ("mod_pitch_noise", "mod_pitch_noiseon"),
    ],
    [
        ("mod_width_lfo", "mod_width_lfoon"),
        ("mod_width_lfowidth", "mod_width_lfowidthon"),
        ("mod_width_env", "mod_width_envon"),
        ("mod_width_autobend", "mod_width_autobendon"),
        ("mod_width_key", "mod_width_keyon"),
        ("mod_width_vel", "mod_width_velon"),
        ("mod_width_wheel", "mod_width_wheelon"),
        ("mod_width_press", "mod_width_presson"),
        ("mod_width_bend", "mod_width_bendon"),
        ("mod_width_vco1", "mod_width_vco1on"),
        ("mod_width_vco2", "mod_width_vco2on"),
        ("mod_width_sub", "mod_width_subon"),
        ("mod_width_noise", "mod_width_noiseon"),
    ],
    [
        ("mod_cutoff_lfo", "mod_cutoff_lfoon"),
        ("mod_cutoff_lfowidth", "mod_cutoff_lfowidthon"),
        ("mod_cutoff_env", "mod_cutoff_envon"),
        ("mod_cutoff_autobend", "mod_cutoff_autobendon"),
        ("mod_cutoff_key", "mod_cutoff_keyon"),
        ("mod_cutoff_vel", "mod_cutoff_velon"),
        ("mod_cutoff_wheel", "mod_cutoff_wheelon"),
        ("mod_cutoff_press", "mod_cutoff_presson"),
        ("mod_cutoff_bend", "mod_cutoff_bendon"),
        ("mod_cutoff_vco1", "mod_cutoff_vco1on"),
        ("mod_cutoff_vco2", "mod_cutoff_vco2on"),
        ("mod_cutoff_sub", "mod_cutoff_subon"),
        ("mod_cutoff_noise", "mod_cutoff_noiseon"),
    ],
    [
        ("mod_amp_lfo", "mod_amp_lfoon"),
        ("mod_amp_lfowidth", "mod_amp_lfowidthon"),
        ("mod_amp_env", "mod_amp_envon"),
        ("mod_amp_autobend", "mod_amp_autobendon"),
        ("mod_amp_key", "mod_amp_keyon"),
        ("mod_amp_vel", "mod_amp_velon"),
        ("mod_amp_wheel", "mod_amp_wheelon"),
        ("mod_amp_press", "mod_amp_presson"),
        ("mod_amp_bend", "mod_amp_bendon"),
        ("mod_amp_vco1", "mod_amp_vco1on"),
        ("mod_amp_vco2", "mod_amp_vco2on"),
        ("mod_amp_sub", "mod_amp_subon"),
        ("mod_amp_noise", "mod_amp_noiseon"),
    ],
];

/// Every permanent id this plugin has retired. Never re-used.
pub const RETIRED_IDS: [&str; 17] = [
    // The nine controls the routing conversion replaced.
    "vcolfo",
    "autobend",
    "pwmdepth",
    "pwmmode",
    "envamount",
    "envpolarity",
    "vcflfo",
    "keytrack",
    "bendfilter",
    // The Follower source's routes, with the external input it followed (2026-09-26).
    "mod_pitch_follower",
    "mod_pitch_followeron",
    "mod_width_follower",
    "mod_width_followeron",
    "mod_cutoff_follower",
    "mod_cutoff_followeron",
    "mod_amp_follower",
    "mod_amp_followeron",
];

/// What a route's amount reads: **what that pair delivers**, in the target's own unit — so the
/// machine's own routes read the machine's numbers at full, the envelope's negative half included
/// (`routing::scale`), and a route the SH-2 never had reads the collection's standard reach. The
/// key's unit is six octaves, so a Key route reads per octave of key.
fn reach(target: usize, source: usize) -> Reach {
    let unit = match target {
        target::PITCH => reading::SEMITONES,
        target::CUTOFF => reading::OCTAVES,
        _ => reading::PERCENT,
    };
    let (above, below) = (
        routing::scale(target, source, 1.0),
        routing::scale(target, source, -1.0),
    );
    if source == source::KEY {
        let per_octave = 12.0 / KEY_UNIT_SEMITONES;
        Reach::per_octave(above * per_octave, unit).below(below * per_octave)
    } else {
        Reach::new(above, unit).below(below)
    }
}

/// A route amount: signed, centred on zero, and **an amount, so it starts there** — the
/// collection's one route parameter (`mxm_modulation_params::reading`), on the travel the pair's
/// offer allows, which on this instrument is always both halves. Smoothed at the 10 ms the controls
/// it replaced had, because it multiplies a signal.
fn amount(target: usize, source: usize) -> FloatParam {
    reading::amount_param(
        format!("{} from {}", TARGET_NAMES[target], SOURCE_NAMES[source]),
        reach(target, source),
        Fader::for_offer(offer(target, source), false),
        10.0,
    )
}

/// Whether a route exists. **Configuration, not an amount**, so its default is the machine's own
/// wiring: six of the eight paths the SH-2 hard-wired that are still here are present in the init
/// patch, at zero depth — all but the pulse width's two, which the owner took off the Init stack
/// (2026-09-27) and which a design that uses them switches on.
fn present(target: usize, source: usize) -> BoolParam {
    BoolParam::new(
        format!("{} from {} on", TARGET_NAMES[target], SOURCE_NAMES[source]),
        INIT_PRESENT.contains(&(target, source)),
    )
}

/// One target's routes: a presence and a signed amount for every source the instrument declares.
#[derive(Params)]
pub struct TargetRoutes {
    #[id = "lfoon"]
    pub lfo_on: BoolParam,
    #[id = "lfo"]
    pub lfo: FloatParam,
    #[id = "lfowidthon"]
    pub lfowidth_on: BoolParam,
    #[id = "lfowidth"]
    pub lfowidth: FloatParam,
    #[id = "envon"]
    pub env_on: BoolParam,
    #[id = "env"]
    pub env: FloatParam,
    #[id = "autobendon"]
    pub autobend_on: BoolParam,
    #[id = "autobend"]
    pub autobend: FloatParam,
    #[id = "keyon"]
    pub key_on: BoolParam,
    #[id = "key"]
    pub key: FloatParam,
    #[id = "velon"]
    pub vel_on: BoolParam,
    #[id = "vel"]
    pub vel: FloatParam,
    #[id = "wheelon"]
    pub wheel_on: BoolParam,
    #[id = "wheel"]
    pub wheel: FloatParam,
    #[id = "presson"]
    pub press_on: BoolParam,
    #[id = "press"]
    pub press: FloatParam,
    #[id = "bendon"]
    pub bend_on: BoolParam,
    #[id = "bend"]
    pub bend: FloatParam,
    #[id = "vco1on"]
    pub vco1_on: BoolParam,
    #[id = "vco1"]
    pub vco1: FloatParam,
    #[id = "vco2on"]
    pub vco2_on: BoolParam,
    #[id = "vco2"]
    pub vco2: FloatParam,
    #[id = "subon"]
    pub sub_on: BoolParam,
    #[id = "sub"]
    pub sub: FloatParam,
    #[id = "noiseon"]
    pub noise_on: BoolParam,
    #[id = "noise"]
    pub noise: FloatParam,
}

impl TargetRoutes {
    /// Every pair for one target, at the init patch.
    pub fn new(t: usize) -> Self {
        Self {
            lfo_on: present(t, source::LFO),
            lfo: amount(t, source::LFO),
            lfowidth_on: present(t, source::LFO_WIDTH),
            lfowidth: amount(t, source::LFO_WIDTH),
            env_on: present(t, source::ENVELOPE),
            env: amount(t, source::ENVELOPE),
            autobend_on: present(t, source::AUTO_BEND),
            autobend: amount(t, source::AUTO_BEND),
            key_on: present(t, source::KEY),
            key: amount(t, source::KEY),
            vel_on: present(t, source::VELOCITY),
            vel: amount(t, source::VELOCITY),
            wheel_on: present(t, source::WHEEL),
            wheel: amount(t, source::WHEEL),
            press_on: present(t, source::PRESSURE),
            press: amount(t, source::PRESSURE),
            bend_on: present(t, source::BEND),
            bend: amount(t, source::BEND),
            vco1_on: present(t, source::VCO1),
            vco1: amount(t, source::VCO1),
            vco2_on: present(t, source::VCO2),
            vco2: amount(t, source::VCO2),
            sub_on: present(t, source::SUB),
            sub: amount(t, source::SUB),
            noise_on: present(t, source::NOISE),
            noise: amount(t, source::NOISE),
        }
    }

    /// One source's presence and amount, in **declared source order**. A `match`, so a sample's
    /// amount read costs a branch rather than building an array of references.
    #[inline]
    fn pair(&self, source: usize) -> (&BoolParam, &FloatParam) {
        match source {
            source::LFO => (&self.lfo_on, &self.lfo),
            source::LFO_WIDTH => (&self.lfowidth_on, &self.lfowidth),
            source::ENVELOPE => (&self.env_on, &self.env),
            source::AUTO_BEND => (&self.autobend_on, &self.autobend),
            source::KEY => (&self.key_on, &self.key),
            source::VELOCITY => (&self.vel_on, &self.vel),
            source::WHEEL => (&self.wheel_on, &self.wheel),
            source::PRESSURE => (&self.press_on, &self.press),
            source::BEND => (&self.bend_on, &self.bend),
            source::VCO1 => (&self.vco1_on, &self.vco1),
            source::VCO2 => (&self.vco2_on, &self.vco2),
            source::SUB => (&self.sub_on, &self.sub),
            _ => (&self.noise_on, &self.noise),
        }
    }

    /// This target's routes, for the interface. `t` is its index, because each row's keyboard scope
    /// is its parameter's permanent id and those are keyed by target.
    pub fn routes(&self, t: usize) -> [Route<'_>; SOURCES] {
        std::array::from_fn(|s| {
            let (present, amount) = self.pair(s);
            Route {
                source: SOURCE_NAMES[s],
                present,
                amount,
                present_id: ROUTE_IDS[t][s].1,
                amount_id: ROUTE_IDS[t][s].0,
            }
        })
    }

    /// Every presence, in source order — for a test that reveals every route.
    pub fn presence_params(&self) -> [&BoolParam; SOURCES] {
        std::array::from_fn(|s| self.pair(s).0)
    }

    /// Whether each route exists. Read **once per interval**, never per sample.
    pub fn presences(&self, t: usize) -> [bool; SOURCES] {
        mxm_modulation_params::presences(&self.routes(t))
    }

    /// Snaps each newly present route's smoother to its stored value.
    ///
    /// **An absent route's smoother is not advanced, so it must not be resumed either.** While the
    /// pair was absent its parameter stayed editable — automation, a preset load — and that moves
    /// the target while the smoother stays wherever the last live sample left it. Resuming would
    /// ramp the route in from a stale depth over a span set by how long it was absent, which is the
    /// host's buffers deciding a sound (mxm-kit's `docs/code-review-notes.md` §7).
    pub fn arm(&self, newly_present: &[bool; SOURCES]) {
        for (s, &now) in newly_present.iter().enumerate() {
            if now {
                let amount = self.pair(s).1;
                amount.smoothed.reset(amount.value());
            }
        }
    }
}

/// All four targets' routes.
#[derive(Params)]
pub struct Routes {
    #[nested(id_prefix = "mod_pitch", group = "Modulation - Pitch")]
    pub pitch: TargetRoutes,
    #[nested(id_prefix = "mod_width", group = "Modulation - Pulse width")]
    pub width: TargetRoutes,
    #[nested(id_prefix = "mod_cutoff", group = "Modulation - Cutoff")]
    pub cutoff: TargetRoutes,
    #[nested(id_prefix = "mod_amp", group = "Modulation - Amplitude")]
    pub amp: TargetRoutes,
}

impl Default for Routes {
    fn default() -> Self {
        Self::new()
    }
}

impl Routes {
    /// The init patch: **six of the machine's hard-wired paths present, every depth at zero.**
    pub fn new() -> Self {
        Self {
            pitch: TargetRoutes::new(target::PITCH),
            width: TargetRoutes::new(target::PULSE_WIDTH),
            cutoff: TargetRoutes::new(target::CUTOFF),
            amp: TargetRoutes::new(target::AMPLITUDE),
        }
    }

    /// The four targets, in declared target order.
    pub fn each(&self) -> [&TargetRoutes; TARGETS] {
        [&self.pitch, &self.width, &self.cutoff, &self.amp]
    }

    /// Which routes are live, for the whole instrument. Once per interval.
    pub fn topology(&self) -> Routing {
        let mut routing = Routing::new();
        for (t, (slot, group)) in routing.present.iter_mut().zip(self.each()).enumerate() {
            *slot = group.presences(t);
        }
        routing.compact();
        routing
    }

    /// The topology for this interval, with every **newly present** route's smoother snapped to its
    /// stored value. `previous` is the topology the last interval ran, which the caller keeps.
    pub fn topology_from(&self, previous: &Routing) -> Routing {
        let routing = self.topology();
        for (t, group) in self.each().into_iter().enumerate() {
            let mut newly = [false; SOURCES];
            for (slot, (&now, &before)) in newly
                .iter_mut()
                .zip(routing.present[t].iter().zip(previous.present[t].iter()))
            {
                *slot = now && !before;
            }
            group.arm(&newly);
        }
        routing
    }

    /// Reads this interval's amounts, **once per interval** and after [`Routes::topology_from`]: each
    /// settled route's here, and each ramping route listed for [`Routes::advance`].
    ///
    /// **A settled smoother is not advanced per sample, because advancing it does nothing**:
    /// nice-plug's `Smoother::next` returns the target and moves no state once a ramp is done, so the
    /// value read here is the one every sample would have read, to the bit. What reading it per sample
    /// does cost is memory — each amount is a `FloatParam` on cache lines of its own, touched for
    /// nothing; how much is for the quiet-machine measurement `BASELINE-M0.md` describes. The host's changes land between buffers, where
    /// this runs (`SAMPLE_ACCURATE_AUTOMATION` is off); an edit the wrapper applies from the editor's
    /// thread in mid-buffer starts its ramp at the next buffer rather than at whichever sample that
    /// thread happened to reach.
    pub fn settle(&self, routing: &mut Routing, ramps: &mut Ramps) {
        let targets = self.each();
        ramps.len = 0;
        ramps.vibrato = 0.0;
        for i in 0..routing.live().len() {
            let (t, s) = routing.live()[i];
            let smoothed = &targets[t as usize].pair(s as usize).1.smoothed;
            if smoothed.is_smoothing() {
                ramps.moving[ramps.len] = (t, s);
                ramps.len += 1;
            } else {
                let settled = smoothed.next();
                routing.amounts[t as usize][s as usize] = settled;
                if (t as usize, s as usize) == (target::PITCH, source::LFO) {
                    ramps.vibrato = settled;
                }
            }
        }
    }

    /// Fills this sample's amounts: **each ramping route's smoother advanced once**, then the mod
    /// wheel's legacy push.
    ///
    /// `wheel` deepens the vibrato route that is already there, which is what the plugin's wheel
    /// always did to the VCO LFO depth — added into that pair's stored depth, so a wheel at zero is
    /// exactly the stored depth (governing plan §5.2). The raw wheel is a routable source beside it.
    ///
    /// **It adds, whichever way the route points**: the lever's vibrato is its own depth
    /// summed with the route's, as the machine's slider and lever depths summed, so a negative route is
    /// partly cancelled rather than deepened. Taking the route's sign instead would step the depth by
    /// twice the push as a swept amount crossed zero.
    #[inline]
    pub fn advance(&self, routing: &mut Routing, ramps: &mut Ramps, wheel: f32) {
        let targets = self.each();
        for &(t, s) in &ramps.moving[..ramps.len] {
            let value = targets[t as usize].pair(s as usize).1.smoothed.next();
            if (t as usize, s as usize) == (target::PITCH, source::LFO) {
                ramps.vibrato = value;
            } else {
                routing.amounts[t as usize][s as usize] = value;
            }
        }
        routing.amounts[target::PITCH][source::LFO] = (ramps.vibrato + wheel).clamp(-1.0, 1.0);
    }

    /// Every routing parameter, named by its permanent id, for the preset layer. **Presets carry
    /// routing**, presences included, or a preset would leave the previous patch's routes behind.
    pub fn parameters(&self) -> Vec<(&'static str, &dyn mxm_preset::ErasedParam)> {
        let mut out = Vec::with_capacity(TARGETS * SOURCES * 2);
        for (t, (group, ids)) in self.each().into_iter().zip(ROUTE_IDS).enumerate() {
            for (route, (amount, presence)) in group.routes(t).into_iter().zip(ids) {
                out.push((amount, route.amount));
                out.push((presence, route.present));
            }
        }
        out
    }
}

/// Which live routes are still ramping this interval, and the vibrato route's own depth before the
/// wheel's push: [`Routes::settle`] fills it and [`Routes::advance`] reads it. The plugin keeps one
/// beside its [`Routing`].
#[derive(Debug, Clone, Copy)]
pub struct Ramps {
    moving: [(u8, u8); TARGETS * SOURCES],
    len: usize,
    vibrato: f32,
}

impl Default for Ramps {
    fn default() -> Self {
        Self {
            moving: [(0, 0); TARGETS * SOURCES],
            len: 0,
            vibrato: 0.0,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use nice_plug::params::Params;

    /// [`ROUTE_IDS`] names exactly what the derive produces, and nothing else.
    #[test]
    fn the_id_table_is_what_the_derive_actually_produces() {
        let params = crate::params::MxmMono02Params::default();
        let real: std::collections::BTreeSet<String> = params
            .param_map()
            .into_iter()
            .map(|(id, _, _)| id)
            .filter(|id| id.starts_with("mod_"))
            .collect();
        let named: std::collections::BTreeSet<String> = ROUTE_IDS
            .iter()
            .flatten()
            .flat_map(|(amount, presence)| [(*amount).to_owned(), (*presence).to_owned()])
            .collect();
        assert_eq!(named, real, "ROUTE_IDS has drifted from the derived ids");
        assert_eq!(named.len(), TARGETS * SOURCES * 2);
    }

    /// **No retired id reappears.** A name whose meaning changed must not come back meaning
    /// something else: an old project would load its value into the new parameter.
    #[test]
    fn no_retired_id_reappears_among_the_parameters() {
        let params = crate::params::MxmMono02Params::default();
        let ids: Vec<String> = params
            .param_map()
            .into_iter()
            .map(|(id, _, _)| id)
            .collect();
        for retired in RETIRED_IDS {
            assert!(!ids.iter().any(|id| id == retired), "`{retired}` is back");
        }
        assert_eq!(ids.len(), 27 + TARGETS * SOURCES * 2, "131 host parameters");
    }

    /// **Every route's depth starts at zero, and the init patch wires the machine's own routes but
    /// the pulse width's** — the parameter defaults and the DSP's `Routing::init` are one statement,
    /// and the Pulse width stack starts empty (the owner, 2026-09-27).
    #[test]
    fn the_init_patch_wires_six_of_the_machines_routes_at_zero_depth() {
        let params = crate::params::MxmMono02Params::default();
        for (t, group) in params.routes.each().into_iter().enumerate() {
            for (route, name) in group.routes(t).iter().zip(SOURCE_NAMES) {
                assert_eq!(
                    route.amount.default_normalised(),
                    0.5,
                    "`{} from {name}` is a depth and must start at zero",
                    TARGET_NAMES[t]
                );
            }
        }
        assert_eq!(params.routes.topology().present, Routing::init().present);
        assert!(
            !params.routes.width.lfowidth_on.value() && !params.routes.width.env_on.value(),
            "the Pulse width stack starts empty"
        );
        let present = |t: usize| {
            (0..SOURCES)
                .filter(|&s| Routing::init().present[t][s])
                .count()
        };
        assert_eq!(
            [
                routing::target::PITCH,
                routing::target::PULSE_WIDTH,
                routing::target::CUTOFF,
                routing::target::AMPLITUDE
            ]
            .map(present),
            [2, 0, 4, 0]
        );
    }

    /// **Remove, edit while absent, re-add: the route arrives at the depth the player set.**
    #[test]
    fn a_re_added_route_arrives_at_its_stored_depth_rather_than_ramping_from_a_stale_one() {
        use nice_plug::params::InternalParamMut;

        let routes = Routes::new();
        assert!(!routes.cutoff.vco1_on.value(), "this pair starts absent");

        const RATE: f32 = 48_000.0;
        unsafe {
            routes.cutoff.vco1_on._internal_set_plain_value(true);
            routes.cutoff.vco1._internal_set_plain_value(0.9);
            routes.cutoff.vco1._internal_update_smoother(RATE, true);
        }
        let routing = routes.topology_from(&Routing::new());
        let mut amounts = routing;
        let mut ramps = Ramps::default();
        routes.settle(&mut amounts, &mut ramps);
        routes.advance(&mut amounts, &mut ramps, 0.0);
        assert_eq!(amounts.amounts[target::CUTOFF][source::VCO1], 0.9);

        unsafe {
            routes.cutoff.vco1_on._internal_set_plain_value(false);
        }
        let absent = routes.topology_from(&routing);
        unsafe {
            routes.cutoff.vco1._internal_set_plain_value(-0.4);
            routes.cutoff.vco1._internal_update_smoother(RATE, false);
        }
        assert!(
            routes.cutoff.vco1.smoothed.is_smoothing(),
            "the edit must leave the smoother mid-ramp, or this proves nothing"
        );

        unsafe {
            routes.cutoff.vco1_on._internal_set_plain_value(true);
        }
        let mut back = routes.topology_from(&absent);
        routes.settle(&mut back, &mut ramps);
        routes.advance(&mut back, &mut ramps, 0.0);
        assert_eq!(
            back.amounts[target::CUTOFF][source::VCO1],
            -0.4,
            "a re-added route must arrive at its stored depth"
        );
    }

    /// **The wheel's push adds, whichever way the route points**, so the depth is continuous as a swept
    /// amount crosses zero. A push that took the route's sign — tried on 2026-09-15, after a review read
    /// *deepens* as *further from zero* — stepped the depth by twice the push at the crossing, and the
    /// next review caught it.
    #[test]
    fn the_wheel_push_adds_the_same_whichever_way_the_route_points() {
        use nice_plug::params::InternalParamMut;

        let routes = Routes::new();
        let depth_at = |amount: f32| {
            unsafe {
                routes.pitch.lfo._internal_set_plain_value(amount);
                routes.pitch.lfo._internal_update_smoother(48_000.0, true);
            }
            let stored = routes.pitch.lfo.value();
            let mut routing = routes.topology_from(&Routing::new());
            let mut ramps = Ramps::default();
            routes.settle(&mut routing, &mut ramps);
            routes.advance(&mut routing, &mut ramps, 0.5);
            (stored, routing.amounts[target::PITCH][source::LFO])
        };
        for amount in [-0.3, -0.001, 0.0, 0.001, 0.3] {
            let (stored, depth) = depth_at(amount);
            assert_eq!(
                depth,
                stored + 0.5,
                "the push at a stored depth of {stored}"
            );
        }
    }

    /// **Reading a settled route once per interval gives what advancing it every sample gave**, to the
    /// bit: through two ramps that start in one interval, cross several and settle, with the wheel
    /// pushing the vibrato route part of the way.
    #[test]
    fn settled_routes_read_once_per_interval_match_advancing_every_sample() {
        use nice_plug::params::InternalParamMut;
        const RATE: f32 = 48_000.0;
        let (fast, slow) = (Routes::new(), Routes::new());
        let topology = fast.topology();
        let (mut a, mut b) = (topology, topology);
        let mut ramps = Ramps::default();
        let mut ramped = 0;
        for interval in 0..24 {
            if interval == 3 {
                for r in [&fast, &slow] {
                    unsafe {
                        r.pitch.lfo._internal_set_plain_value(0.6);
                        r.pitch.lfo._internal_update_smoother(RATE, false);
                        r.cutoff.env._internal_set_plain_value(-0.8);
                        r.cutoff.env._internal_update_smoother(RATE, false);
                    }
                }
            }
            fast.settle(&mut a, &mut ramps);
            let wheel = if (6..14).contains(&interval) {
                0.3
            } else {
                0.0
            };
            for sample in 0..64 {
                fast.advance(&mut a, &mut ramps, wheel);
                // The reference: every live smoother advanced every sample, then the push.
                let groups = slow.each();
                let live = b.live().to_vec();
                for &(t, s) in &live {
                    b.amounts[t as usize][s as usize] =
                        groups[t as usize].pair(s as usize).1.smoothed.next();
                }
                let vibrato = &mut b.amounts[target::PITCH][source::LFO];
                *vibrato = (*vibrato + wheel).clamp(-1.0, 1.0);
                for &(t, s) in b.live() {
                    let (t, s) = (t as usize, s as usize);
                    assert_eq!(
                        a.amounts[t][s].to_bits(),
                        b.amounts[t][s].to_bits(),
                        "interval {interval}, sample {sample}: ({t}, {s})"
                    );
                }
                if slow.cutoff.env.smoothed.is_smoothing() {
                    ramped += 1;
                }
            }
        }
        assert!(
            ramped > 64 * 3,
            "the premise: the ramp crossed intervals, {ramped} samples"
        );
        assert_eq!(a.amounts[target::CUTOFF][source::ENVELOPE], -0.8);
    }

    /// **A control-map role may take a route's amount only where Init wires that route**, or its
    /// knob is dead on a fresh instance.
    #[test]
    fn a_control_map_role_never_points_at_a_dead_route() {
        let text = include_str!("../control-map.json");
        let params = crate::params::MxmMono02Params::default();
        let mut named = 0;
        for (t, group) in params.routes.each().into_iter().enumerate() {
            for (route, (amount, presence)) in group.routes(t).into_iter().zip(ROUTE_IDS[t]) {
                if text.contains(&format!("\"{presence}\"")) {
                    named += 1;
                }
                if text.contains(&format!("\"{amount}\"")) {
                    named += 1;
                    assert!(
                        route.is_present(),
                        "the control map binds a role to {amount}, which Init does not wire"
                    );
                }
            }
        }
        // Four ids for five roles: the filter's LFO amount and the LFO's filter depth name one
        // route. The two PWM depth roles are unfilled since Init routes nothing to the pulse width.
        assert_eq!(named, 4, "the map names {named} routing ids");
    }

    /// **A route reads what its pair delivers**, in the target's unit, the machine's numbers at full
    /// — and a reading typed back in lands on the amount it came from.
    #[test]
    fn a_route_reads_what_its_pair_delivers_and_reads_back() {
        use mxm_preset::ErasedParam;
        let r = Routes::new();
        let cases: [(&FloatParam, f32, &str); 15] = [
            // The machine's own, at their controls' reach.
            (&r.pitch.lfo, 1.0, "+7.00 st"),
            (&r.pitch.autobend, 1.0, "-12.00 st"),
            (&r.width.lfowidth, 1.0, "-45 %"),
            (&r.width.env, 1.0, "-45 %"),
            (&r.cutoff.env, 1.0, "+10.00 oct"),
            (&r.cutoff.env, 0.0, "-2.75 oct"),
            (&r.cutoff.lfo, 1.0, "+4.00 oct"),
            (&r.cutoff.key, 1.0, "+1.20 oct/oct"),
            (&r.cutoff.bend, 1.0, "+2.00 oct"),
            // Added ones, at the collection's standard reach.
            (&r.pitch.key, 1.0, "+12.00 st/oct"),
            (&r.pitch.wheel, 1.0, "+12.00 st"),
            (&r.cutoff.vel, 1.0, "+4.00 oct"),
            (&r.width.key, 1.0, "-9 %/oct"),
            (&r.amp.vel, 1.0, "+100 %"),
            (&r.amp.key, 1.0, "+20 %/oct"),
        ];
        for (param, normalised, expected) in cases {
            let text = ErasedParam::format(param, normalised);
            assert_eq!(
                text,
                expected,
                "{} at {normalised}",
                ErasedParam::name(param)
            );
            let back = param
                .string_to_normalized_value(&text)
                .expect("the reading parses");
            assert!(
                (back - normalised).abs() < 1e-3,
                "{}: {text} read back as {back}",
                ErasedParam::name(param)
            );
        }
    }

    use mxm_plugin_test::routing_checks;

    /// **Every route parameter says what the DSP does** — the modulation standard's plugin half:
    /// each pair's travel is its offer's, its reading carries its target's unit and states what
    /// `mxm_mono_02_dsp::conformance` measures the voice's own graph delivering, and every reading
    /// survives the host's round trip.
    ///
    /// Falsified before trusted: with the cutoff reading's reach left at the envelope's ten octaves
    /// for Velocity, it names that pair.
    #[test]
    fn every_route_parameter_says_what_the_dsp_does() {
        let routes = Routes::new();
        let groups = routes.each();
        if let Err(failures) =
            routing_checks::amounts(&mxm_mono_02_dsp::conformance::Declared, |target, source| {
                Some(groups[target].pair(source).1)
            })
        {
            panic!("{} failure(s):\n{}", failures.len(), failures.join("\n"));
        }
    }

    /// **Every reading survives the host's round trip, a rounded zero included**: printed, parsed and
    /// printed again, it is the same text — at amounts either side of zero, not only the round numbers.
    /// A plain signed format printed `-0 %` there, which parses to zero and prints `+0 %`, and
    /// `clap-validator`'s `param-conversions` fails on that whenever its random values land in the
    /// sliver (`mxm_modulation_params::signed`).
    #[test]
    fn every_reading_survives_the_hosts_round_trip_a_rounded_zero_included() {
        let routes = Routes::new();
        let check = |param: &FloatParam| {
            for normalised in [
                0.0f32, 0.25, 0.4999, 0.49999, 0.5, 0.50001, 0.5001, 0.75, 1.0,
            ] {
                let text = param.normalized_value_to_string(normalised, true);
                let back = param
                    .string_to_normalized_value(&text)
                    .unwrap_or_else(|| panic!("{}: {text} does not parse", param.name()));
                assert_eq!(
                    text,
                    param.normalized_value_to_string(back, true),
                    "{} at {normalised}",
                    param.name()
                );
            }
        };
        for group in routes.each() {
            for source in 0..SOURCES {
                check(group.pair(source).1);
            }
        }
    }

    /// The routes the player's tests reach by display name carry the names those tests use.
    #[test]
    fn the_headline_routes_are_named_as_the_players_tests_find_them() {
        let r = Routes::new();
        assert_eq!(r.width.lfowidth.name(), "Pulse width from LFO to width");
        assert_eq!(r.cutoff.env.name(), "Cutoff from Envelope");
        assert_eq!(r.cutoff.key.name(), "Cutoff from Key");
        assert_eq!(r.pitch.lfo.name(), "Pitch from LFO");
        assert_eq!(r.pitch.autobend.name(), "Pitch from Auto bend");
        assert_eq!(
            ROUTE_IDS[target::PULSE_WIDTH][source::LFO_WIDTH].0,
            "mod_width_lfowidth"
        );
    }
}
